### ISSUE TITLE
Code generation fails with latest Azure OpenAI 

### ISSUE THREAD

**Issue by jpalvarezl** [Azure/autorest.java#2273] opened 2023-08-15 13:24 UTC
## Description

While bringing in the latest changes in this branch for the Azure OpenAI SDK rest API spec (expected to be merged in this [PR](https://github.com/Azure/azure-rest-api-specs/pull/25271/commits) ) into the Java Azure OpenAI SDK ([link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/openai/azure-ai-openai)) running the code generation  steps:

- `\eng\common\scripts\TypeSpec-Project-Sync.ps1`
- `\eng\common\scripts\TypeSpec-Project-Generate.ps1`

The second script fails with the following error:

![image](https://github.com/Azure/autorest.java/assets/11056031/57e57a83-f866-4301-90c0-d95d9aa61dcf)

## Expected behaviour

The TSP project in isolation compiles fine with a typespec compiler version of `v0.47.0`

## Additional context

The source of the issue appears to be the usage of a `union` type between two models. See [here](https://github.com/Azure/azure-rest-api-specs/pull/25271/files#diff-dc5836bc2f2bc7d21322b10726611deb23591b7f0d60d65e09afdcaeb29bd224R74).

## Repro

Use the following `tsp-location.yaml` values for a repro of the error:

```yaml
commit: abde69c39810669c9a0d771bfdd8fb262b6c4de0
repo: trrwilson/azure-rest-api-specs
```

The latest commit in this branch has reverted the problematic changes. [Here](https://github.com/Azure/azure-rest-api-specs/pull/25271/commits/0d3d201639b9e7f3f448bbd08b1fe2fd461ecf49) you can see them in isolation.

**Comment by weidongxu-microsoft** [comment] 2023-08-16 02:10
acknowledged, will try make a 0.8.9 today

emitter-package.json update in SDK repo may take one more day.

**Comment by weidongxu-microsoft** [comment] 2023-08-16 04:08
The cause is actually this `EnumMember` as type
https://github.com/Azure/azure-rest-api-specs/blob/0d3d201639b9e7f3f448bbd08b1fe2fd461ecf49/specification/cognitiveservices/OpenAI.Inference/models/azure.cognitive.search.options.tsp#L67

Note that this usage is similar to [discriminator](https://microsoft.github.io/typespec/standard-library/built-in-decorators#@discriminator), as you have this as well https://github.com/Azure/azure-rest-api-specs/blob/0d3d201639b9e7f3f448bbd08b1fe2fd461ecf49/specification/cognitiveservices/OpenAI.Inference/models/azure.chat.extensions.tsp#L45

**Comment by weidongxu-microsoft** [comment] 2023-08-16 07:22
@jpalvarezl 

Fixed in 0.8.10. PR to bump version in SDK repo is here https://github.com/Azure/azure-sdk-for-java/pull/36025. The issue will be solved when you merge this PR.

**Comment by jpalvarezl** [comment] 2023-08-16 08:08
Really appreciate the promptness!

**Closed** 2023-08-17 01:28 UTC
Labels: DPG
