### ISSUE TITLE
Replace some naming logic with modelerfour namings

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#533] opened 2020-03-11 19:20 UTC
There are lots of naming options in https://github.com/Azure/autorest.modelerfour/tree/master/modelerfour#modelfour-options that may be able to help trim down our namer.

**Comment by alzimmermsft** [comment] 2024-06-07 20:22
Closing as the issue is vague and old.

**Closed by alzimmermsft** 2024-06-07 20:22 UTC
Labels: v4
